version: '3.9'

services:

  postgresql:
    container_name: db
    image: postgres:16
    ports:
      - "7979:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=instagram